#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Sapan Upadhyay"
email = "sapan.upadhyay@gusto.com"

[ui]
editor = "nvim"
pager = "less -FRX"
diff.format = "git"

[signing]
behavior = "own"
backend = "ssh"

[git]
auto-local-bookmark = false

[revset-aliases]
'trunk()' = 'latest(remote_bookmarks(exact:"main", exact:"origin"))'

[aliases]
l = ["log", "-r", "trunk()..@ | ancestors(bookmarks(), 2)"]
s = ["status"]
d = ["diff"]
